### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/tc/metadata.json'

### ISSUE THREAD

**Issue by caixxiong** [AaronZ345/TCSinger#8]
```python
Traceback (most recent call last):
  File "/data/dsmdla100sx0216/xiong/codes/TCSinger/inference/style_control.py", line 238, in <module>
    StyleControl.example_run()
  File "/data/dsmdla100sx0216/xiong/codes/TCSinger/inference/style_control.py", line 212, in example_run
    items_list = json.load(open(f"{hparams['processed_data_dir']}/metadata.json"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/tc/metadata.json'
```
执行readme中给的inference脚本报错了：`python inference/style_control.py --config egs/sdlm.yaml  --exp_name checkpoints/SDLM` ,作者可以把这个metadata.json文件传上来吗？以及再顺便给几个e2e推理的例子？

**Comment by AaronZ345** [comment]
抱歉不能提供原始的metadata，你可以使用GTSinger提供的metadata进行拼接，进行训练和推理
